### ISSUE TITLE
Patreon pivot from Ura to Identihub

### ISSUE THREAD

**Issue by elioqoshi** [uradotdesign/task-management#10]
Our Patreon is currently helping a bit financially, however we haven't been keeping our supporters up to date much. We also have done quite a few pro-bono jobs in the past which our Patreon could finance. I'd propose to change our Patreon model from doing free design to developing Identihub and offering free hosting for projects which need (based on feedback from Patrons)

We could also implement feature requests or take them into considerations for Identihub based on Patron feedback.

This should be ready by 3 December

**Comment by kominoshja** [comment]
Reminder that the deadline for this is tomorrow.

**Comment by AnXh3L0** [comment]
Elio finished this earlier on. Closing issue.
