### ISSUE TITLE
Identihub Alpha version soft launch

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#11]
Materials for the external communication of the launch of Identihub project. Checklist as following:

-identihub.co website final check: @AnXh3L0 
- press release: @silvaarapi & Redon
- communication plan (brainstorming session): @elioqoshi, Redon & @silvaarapi 
- blog post on ura.design website: @silvaarapi 

Deadline: 15.12.2017.

**Comment by rskikuli** [comment]
Regarding the communication plan, here are some of the elements I propose to proceed:

**Press release**

- A draft press release is also on the task list and will be shared here. All the shared material will be based on the final version of the press release. 

**Websites**

- opensource.com (article based on the press release);
- itsfoss.com;
- www.producthunt.com (important medium);
- www.opensourcedesign.net (important medium);
- http://www.linuxplanet.com;
- https://www.linux.com/;
- http://www.freeopensourcesoftware.org
- pcworld.al;

**Mailing lists:**

- FLOSSK mailing lists;
- Open Labs mailing list;
- Prishtina Hackerspace mailing list;
- LibreOffice mailing list (design);
- Mozilla Mailing list (design team);
- Hackerspace.gr mailing list;
- ELLAK.gr mailing list.

**Social media:**

- twitter hashtag proposed: IdentuhubA
- do we need a dedicated Twitter acocunt? Do we have the resources to handle it at the moment? Thoughts? 
- Albanian Developers FB page (sharing of the announcement);

**Identihub newsletter**

- your engagement is needed here @silvaarapi ;
- content based on the press release.

The above list needs to be expanded further in the next days.

**Comment by elioqoshi** [comment]
I definitely don't think we should launch it so widely for anything less than a Beta release (opensource dot com before we have a Beta? That's way too risky)

Once we are on track with our new developer and have fixed some critical things which are blockers for contributors right now, I'd go ahead with reaching out to communities we collaborate with to speed up development and outreach, but we are very far away from a wide outreach with such prestigious outlets mentioned above I'd say.

**Comment by rskikuli** [comment]
Ok.

**Comment by elioqoshi** [comment]
This is 8 months old and we have a kind of different strategy for Identihub now so let's close this as it doesn't reflect our roadmap anymore
