### ISSUE TITLE
Newsletter #1 December 2017

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#12]
Preparation, development and send out of the first edition of our newsletter. Tasks include:

- content (most important story we want to share): @silvaarapi 
- design, technical structure and testing: @AnXh3L0 

This will be the first edition of our newsletter which means we will need a lot of testing before sending it out.

Deadline for preparation and send out: 20.12.2017

**Comment by silvaarapi** [comment]
I'm creating this pad with some bullet points for content of the newsletter, if anyone from team has any suggestions about what should be included there, please add your notes:

https://pad.ura.design/p/newsletter-general

**Comment by rskikuli** [comment]
First newsletter sent. @AnXh3L0 we need to show the newsletter archive on our website. Closing this.
