### ISSUE TITLE
Andis Rado website development

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#13]
Website design and development for www.andisrado.com.

**Domain & hosting (actual status)**
- www.andisrado.com
- for domain ownership: ask Redon

**Content:**
- based on the actual website www.andisrado.com
- photos and other content: Andis.

**Features:**
- mobile and tablet friendly
- https for more security (needs to be easy to update)

**Deadlines:** 
Research & brainstorming: by 15.12.2017
Live: 15.01.2018

**Comment by silvaarapi** [comment]
@AnXh3L0 shall we arrange a meeting for the next week with Andis in order to gather all the necessary information and then start making some research on the new theme?

**Comment by AnXh3L0** [comment]
@silvaarapi unfortunately I'm leaving on Monday morning and won't be in Tirana until the second week of January.

**Comment by rskikuli** [comment]
@AnXh3L0 need to refresh the work on this. How about a new deadline: May 2018? Is it realistic?

**Comment by elioqoshi** [comment]
We miss information from Andis on this. He confused me with different things in person from what he wrote in the emails. Please handle the communication that it's how he imagines it and we can start implementing it.

**Comment by rskikuli** [comment]
Asked for a meeting for week 17.04.2018. Will follow up.

**Comment by rskikuli** [comment]
@AnXh3L0 we need to refresh the work on this. How about a new deadline?

**Comment by rskikuli** [comment]
We need to move forward with this. Let's coordinate @AnXh3L0 
Deadline for going live: 15.08.2018

**Comment by AnXh3L0** [comment]
We need to follow up with Andis for this, he was a bit undecided in his last email. Will communicate with him today and put you on CC.

**Comment by elioqoshi** [comment]
This has been staggering due to lack of time from Andis' side. We can open it again when needed
