### ISSUE TITLE
Libre Graphics Meeting 2018 presence

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#14]
About the event found from [this twitter post](https://twitter.com/LGMeeting/status/935152812001984516): 

===
The 2018 Libre Graphics Meeting (LGM) will take place at the end of April in Seville, Spain. This annual gathering is an opportunity for teams, contributors and practitioners involved in Libre Graphics to work together, share experiences, and hear new and inspiring ideas.
By libre Graphics we mean “free, Libre and Open Source tools for creative uses”. LGM is not just about software, but extends to standards and file formats used in creative work.
Participants in LGM include developers, designers, academics, and activists. People from around the world who are passionate about Free/Libre tools and their creative applications.

LGM 2018 will take place in two venues with small and medium spaces, and on the first day there will be a conference hall as well. Given these constraints we will prioritize workshops and other interactive formats this year.
Each meeting begins with a joint session that brings together everything that’s happened in our wide landscape over the last year. Instead of slots for general updates on the various software projects, we invite every team to submit two slides (maximum) with a short explanatory text that showcases the progress made over the past year.

For first-time presenters, and particularly big or new topics in established projects, we encourage additional stand-alone submissions.

**We are looking for:**
    ❧ Reflections and practical sessions on promoting the philosophy and use of Libre Graphics tools.
    ❧ Technical presentations and workshops for developers.
    ❧ Showcases of excellent work made using Libre Graphics tools.
    ❧ New tools and workflows for graphics and code.
    ❧ Reflections on the activities of existing Free/Libre and Open Source communities.

**Available formats (times include Q&A):**
    ❧ Entry for State of Libre Graphics (1-2 slides)
    ❧ Presentations (20 minutes)
    ❧ Birds of a Feather (BoF), Workshops, Hackathons (1-2 hours)
    ❧ Lightning talks (5 minutes, selected at the event unconference style)

**Submission details**
The deadline for submissions is the 10th January 2018, and participants will be notified by the end of January 2018. Link: http://libregraphicsmeeting.org/2018/call-for-participation/

===

Ura definitely needs to be present here. Let's work on a proposal @elioqoshi .
Documentation and online presence by @silvaarapi .

**Comment by AnXh3L0** [comment]
Elio has applied for this conference, will update us later.

**Comment by rskikuli** [comment]
We will not attend this. Closing the issue.
