### ISSUE TITLE
Digital Ocean: email for sponsorship 

### ISSUE THREAD

**Issue by silvaarapi** [uradotdesign/task-management#15]
We should sent an email to Digital Ocean to ask for some help with by sponsoring us with the services we need to host. 

- I'll prepare a draft email
- The draft should be reviewed and sent afterwards @rskikuli  @elioqoshi 

Deadline by 10.12.2017

**Comment by silvaarapi** [comment]
I prepared a draft email for this, you can read it here: https://pad.ura.design/p/digital-ocean-sponsorship

@elioqoshi @rskikuli when you find some time please take a look

**Comment by elioqoshi** [comment]
@silvaarapi that looks very solid, thanks for that.

Should be good to go out on Monday, 11th December. What do you think?

**Comment by silvaarapi** [comment]
I contacted DigitalOcean team today, hoping to get an answer the soonest. Will update you as soon as they reply.

**Comment by AnXh3L0** [comment]
Updating issue, we got a positive answer from Digital Ocean, closing this.
