### ISSUE TITLE
Ura company presentation 2017 - 2018

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#17]
We need to have a presentation featuring basic information about what we do, how we do it and also some of the main works and clients we have worked with since the beggining of Ura. 

Content: @elioqoshi & Redon
Design: @AnXh3L0 

Deadline: 15.01.2018

**Comment by rskikuli** [comment]
Proposed content:

- page about our philosophy of work;
- Ura team;
- where are we specialised (skills);
- main projects so far (@elioqoshi your input here is needed);
- side projects and why we do them.

Material format: easily editable (.odt)?
What do you think?

**Comment by rskikuli** [comment]
This is overdue. @elioqoshi please share main projects that you think have more value to be shared. 
We need to work hands on this in the next face to face meeting and move it forward.

**Comment by rskikuli** [comment]
Guys just ping-ing you for this @elioqoshi @AnXh3L0. I'm researching a bit on the format we might want to present this.

**Comment by elioqoshi** [comment]
I really don't think this is a priority. Right now, this makes sense if we want to attract more potential clients/users/partners. We actually are not really striving for that right now as we have enough projects to juggle around this. I would say we should revisit this mid February after FOSDEM

**Comment by elioqoshi** [comment]
We should have this ready after the Work Week I guess since it's needed for the conference season.

**Comment by elioqoshi** [comment]
This is also dependent on: https://github.com/uracreative/task-management/issues/78

**Comment by elioqoshi** [comment]
We might open up this again next year once we get a chance. For now we have been doing okay already.
