### ISSUE TITLE
add SSL to Identihub landing page

### ISSUE THREAD

**Issue by elioqoshi** [uradotdesign/task-management#18]
there is a way to add SSL to custom domain github pages. We should do that:
https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by elioqoshi** [comment]
Since this is kinda screwed up as a process we should probably skip it for now and maybe host the production version on our server where we have full control

**Comment by AnXh3L0** [comment]
Agreed, I think we should leave this for later when we'll have a solid and usable product so we can present it alongside it.

**Comment by kominoshja** [comment]
One possible solution to this would be to have it in our server and to configure it in a way that it automatically fetches new code from GitHub. That way we can also have SSL.
@elioqoshi @AnXh3L0 ?

**Comment by AnXh3L0** [comment]
I'm ok with that @Borisbudini but it's low priority for the moment. I would rather we used the time to work on higher priority issues.

**Comment by kominoshja** [comment]
This solution i proposed has been implemented and https works. However the images are broken. @AnXh3L0 can you please fix the theme?

**Comment by kominoshja** [comment]
Closing this issue as it's done 
https://identihub.co/
