### ISSUE TITLE
Portfolio setup

### ISSUE THREAD

**Issue by AnXh3L0** [uradotdesign/task-management#2]
As discussed, we need to work on the Ura Design portfolio featuring our past works.

I am looking for alternative WordPress plugins (MediaGrid plugin) and will begin implementing it ASAP.

**Comment by rskikuli** [comment]
@AnXh3L0 this makes sense to have the same deadline with the new website. What's the estimation?

**Comment by AnXh3L0** [comment]
This is on the same track as the new website, meaning it is undergoing at the moment. We can close this after we officially launch the new website (will require further polishing as time goes by).

**Comment by elioqoshi** [comment]
I think we can close this after we implemented all past works we want to show here.

**Comment by rskikuli** [comment]
This is work week April 2018 material. Adding this on the task list.

**Comment by elioqoshi** [comment]
Yes definitely.
We should add right now (before Work Weekend)

- Insignary
- ProTip
- Enigmail
- SIT
- WorldBrain 

There is more material, but we can leave that for later as well.

**Comment by elioqoshi** [comment]
Although more projects can be added, the structure is there and works well. Closing
