### ISSUE TITLE
Image template for social media and blog posts

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#20]
We need to have a concept for the template that will be used for posts on our social media channels, newsletter and blog posts. This needs to be different but at the same time to keep the same look and feel in terms of design. 

Deadline: 6.12.2017

**Comment by rskikuli** [comment]
@marianaballa have a look on this and follow up with @AnXh3L0, or contact me for help. Update here please. Let's close this soon.

**Comment by rskikuli** [comment]
@AnXh3L0 @marianaballa please an update on this.

**Comment by elioqoshi** [comment]
This is still kind of important but directly related to implementing Meta info for all pages so they appear correct when sharing on social media.

**Comment by elioqoshi** [comment]
Closing as the website meta info should offer this itself.
