### ISSUE TITLE
Ura Work Week Nov. 2017 blog post

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#21]
Please proceed with a blog post that will document the activities during Ura Work Week in November 2017. The main image of the blog post should be from this issue https://github.com/uracreative/task-management/issues/20 - @AnXh3L0 should help on this. Proposed structure (not obligatory to be followed):

- what is Ura work week;
- what happened;
- was there any positive change during the work week (working in the open might be mentioned, but shortly since there will be another dedicated post about this)?
- next steps for our team. 

Don't forget the group photo.

**Comment by silvaarapi** [comment]
I wrote a draft for the blog post here: https://pad.ura.design/p/ura-work-week-nov-2017-blog-post

@rskikuli please review it when you can so we can proceed with publishing it.

**Comment by rskikuli** [comment]
This is now published: https://ura.design/2018/01/09/ura-work-week-november-2017/. Closing this.
