### ISSUE TITLE
transfer identihub.co from Anxhelo to Ura GitHub organization

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#23]
Right now the repo files of the identihub.co website (which is a Github page) are at @AnXh3L0 Github account. We need to transfer these files at Ura repo. 
@Borisbudini please overview the process to make sure that everything looks good. 

Deadline: 6.12.2017.

**Comment by elioqoshi** [comment]
I'd give this a bit more time as we have higher priorities for now. This is more like housekeeping, not actual content. So let's push this down a week later, 13 December

**Comment by AnXh3L0** [comment]
The files have been transferred from my GitHub page to Ura's repo and the paths/pages have been fixed. At the moment the page is being linked to identihub.co.

**Comment by AnXh3L0** [comment]
Closing this since the process is done.
