### ISSUE TITLE
Add newsletter registration to Identihub website

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#24]
Please add the functionality of 'email registration' to the newsletter for anyone interested to the latest news of Identihub. @silvaarapi please coordinate and make sure the listof identihub newsletter and Ura are not confused.

Deadline: 15.12.2017

**Comment by AnXh3L0** [comment]
The newsletter subscription form is now active in the Identihub website and saves the data using a secret token since GitHub pages doesn't allow php or server-side coding, only static data.

Further polishing is to be expected but for the moment is more than usable and working properly.

**Comment by AnXh3L0** [comment]
Closing this issue since the task was completed.
