### ISSUE TITLE
update team members on Ura Website

### ISSUE THREAD

**Issue by elioqoshi** [uradotdesign/task-management#25]
we should update the team members on our website with the current ones.

**Comment by AnXh3L0** [comment]
The team members have been updated in the website, further polishing is needed still as discussed in the chat, waiting for input from Boris.

**Comment by kominoshja** [comment]
Updated, you must have access now.

**Comment by elioqoshi** [comment]
@Borisbudini let's make sure to have a quicker turnaround if possible. Thanks.
@AnXh3L0 can you have a look again?

**Comment by AnXh3L0** [comment]
Images have been polished, including the events plugin at the bottom at the page that now displays correctly also in desktop screen size. Closing this.
