### ISSUE TITLE
Add new profile pics at webmail infrastructure

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#26]
We alongside with #19 we need also to have our photos from the photo shooting session in the email platform we use. Ask for final photos from @AnXh3L0 . Please report here when finished. 

Deadline: 2.12.2017

**Comment by elioqoshi** [comment]
Done on my end

**Comment by AnXh3L0** [comment]
Did it a few days ago too.

**Comment by AnXh3L0** [comment]
Updates on this @rskikuli @Borisbudini @silvaarapi?

**Comment by kominoshja** [comment]
I changed mine since the photo shooting day.

**Comment by kominoshja** [comment]
I'm going ahead and closing this issue since it is completed
