### ISSUE TITLE
Fix Readme file for the Identihub website repo

### ISSUE THREAD

**Issue by AnXh3L0** [uradotdesign/task-management#27]
We need a new README file for the Identihub website [repo](https://github.com/uracreative/identihub.co) to reflect what the repo is about and more details about Identihub.

**Comment by AnXh3L0** [comment]
It seems this should be postponed for later, it is not important right now.

**Comment by kominoshja** [comment]
I can take this task
Deadline 15.02.2018

**Comment by kominoshja** [comment]
**> Here's the text i have written so far. Let me know if i should go ahead with it**


# Identihub.co

Identihub is an open-source web platform for brand and assets management. It is being developed by Ura Design, an open-source design agency.
This is the repo from where Identihub's code is taken.


---

The site runs on Jekyll.
The code is taken from the repo and then compiled on our servers.

**Comment by elioqoshi** [comment]
Let's just go ahead with this. Thanks

**Comment by AnXh3L0** [comment]
Readme file updated at the identihub.co repo.

**Comment by rskikuli** [comment]
@AnXh3L0 if this is done please close the issue. Thanks guys!
