### ISSUE TITLE
UI Design work for Muonium

### ISSUE THREAD

**Issue by elioqoshi** [uradotdesign/task-management#29]
On the Open Source Design board a new job was created for a UI design update for Muonium, a fully open source and end-to-end encrypted cloud storage software & provider.

The gig is paid so we might want to reach out to them to do the job.

https://muonium.io/#!/

Let's prepare an email to reach out to them and talk details. @silvaarapi can you draft something up?

https://github.com/opensourcedesign/jobs/pull/267

**Comment by silvaarapi** [comment]
Hey @elioqoshi , 

I prepared a draft for this here: https://pad.ura.design/p/muonium-design-work-draft-email 

When you find some time take a look and let me know if I should proceed with reaching them out

**Comment by rskikuli** [comment]
Do you have info on this @elioqoshi ?

**Comment by elioqoshi** [comment]
We haven't followed up on this. Closing.
