### ISSUE TITLE
Work Week blog post - working in the open

### ISSUE THREAD

**Issue by silvaarapi** [uradotdesign/task-management#3]
Write a blog post about the way our team works, how we operate, project management in Github - and our team working in the open.

**Comment by AnXh3L0** [comment]
Ping @silvaarapi. Have you had time to deal with this issue?

**Comment by elioqoshi** [comment]
Yeah this is overdue already. Please updates.

**Comment by AnXh3L0** [comment]
Blogpost has been published, closing this.
