### ISSUE TITLE
Setup Identihub Dev Instance

### ISSUE THREAD

**Issue by elioqoshi** [uradotdesign/task-management#30]
We should set up dev.identihub.co to push changes and break things quick and fast before we push stable updates to the demo. With the new DigitalOcean sponsorship, we should be able to afford this.

@borisbudini please set up a new fresh Identihub installation on a 5 USD droplet.

**Comment by kominoshja** [comment]
You can access the new server at dev.identihub.co
Apologies for the delayed response.
Closing this issue.
