### ISSUE TITLE
Domain access issue with www.identihub.co

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#31]
![identihub screenshot from 2017-12-27 19-16-30](https://user-images.githubusercontent.com/17770262/34390081-c253a4ce-eb3d-11e7-94fc-1d2964cba794.png)
When accessing the domain www.identihub.co the website doesn't work, see screenshot. 

- OS: Ubuntu
- Browser: Firefox 57.0.1
Please review and follow up. 

Deadline: 4.01.2017

**Comment by kominoshja** [comment]
Hey @rskikuli. Please allow some time for the record to update. Thanks
