### ISSUE TITLE
Apply for Open Source Initiative Affiliate 

### ISSUE THREAD

**Issue by elioqoshi** [uradotdesign/task-management#33]
Let's explore the possibilities to become Affiliates of OSI:
https://opensource.org/AffiliateRequirements

The process should take some time but we should be eligible, especially with Identihub.

**Comment by rskikuli** [comment]
Was reading with @marianaballa  the requirements for this. We need to be one of the following: 

- a Non-Profit Organization;
- an Educational Institution;
- a User Community.

All need paperwork to show that in a legal way we are one of the above @elioqoshi. Let's keep this on hold?

**Comment by elioqoshi** [comment]
Oh seems I missed that. Yeah let's close this and reopen it when needed
