### ISSUE TITLE
Promotional material design for Ura

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#37]
Following the growing presence of the team in different conferences we need to have some tools that communicate and promote Ura easier and even better. This is a similar task with #36. 
Here is a list of materials needed to be designed (or edited from actual designs) especially now that Fosdem 2018 is close:

- stickers;
- business cards (generic, but with a slogan or call to action);
- Ura 3D printed material design (maybe post at thingyverse as well?);
- other promo materials for events and conferences (branded balloons, tshirts etc)

Please proceed first with proposals (here) before finalizing the materials. @elioqoshi ideas about printing specs welcome.

All the above should be published in a Github repo:

- in a preview format;
- with the source file for easy editing in the future - open source format;
- ready to be sent for printing;

Deadline: 13.01.2018.

**Comment by rskikuli** [comment]
All team members should have stickers for Ura and Identihub (thanks Elio). 
@AnXh3L0 please make sure to habe the stickers in our Identihu project page and/or Github. @elioqoshi where is the best place to document those? I would say Identihub... 
Next on the line: 

- Ura 3D printed material design (maybe post at thingyverse as well?);
- other promo materials for events and conferences (branded balloons, tshirts etc). This needs some research. 


All the above should be published in a Github repo (or Identihub?):

- in a preview format;
- with the source file for easy editing in the future - open source format;
- ready to be sent for printing;

Important to have an update on this during work week.

**Comment by elioqoshi** [comment]
What does it mean to have the stickers on our Identihub and GitHub? The stickers are just the logos.

I like the idea of 3D Prints. Keychains would be a good start. 

Wikimedia commons supports 3D files (STL) now as well

**Comment by rskikuli** [comment]
It means that we need to have them as files that are ready for print including guidance that shows where the paper is cut and also a preview file ideally. If we send just the logo to be printed without guidance they might be printed in a wrong way from the printing house. Anyway, if you think it is too much details in terms of documentation  and the process is self explanatory we should close the issue.

**Comment by elioqoshi** [comment]
We end up doing those specs case by case and have not worked with producers which screw them up. Idenithub is not ready for that and it's too much effort for something which we don't urgently need right now. So closing this.
