### ISSUE TITLE
Ura blog post: wishes for 2018

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#40]
New short blog post with wishes for the New Year. Add logos featured at Logobridge as a small 'gift' to the open source design community - collaboration with @elioqoshi @AnXh3L0 . 

Deadline: 11.01.2018. High priority due to the fact that this was initiated late.

**Comment by AnXh3L0** [comment]
Ping, where are we with this?

**Comment by marianaballa** [comment]
@AnXh3L0 here is the text that I prepared with overview from Redon:
https://cloud.ura.design/apps/files/?dir=/Team/Pads&fileid=3526

Kindly prepare a GIF that is related either to 2018 or Logobridge 

Thanks
