### ISSUE TITLE
Identihub 404 page design

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#41]
When you visit a randon page like https://demo.identihub.co/project/testingthispage the error page that appears is quite... bad. Please redesign a well designed 404 error page with a smart copy. Inspiration: https://www.smashingmagazine.com/2014/08/a-better-404-page/ and https://www.canva.com/learn/404-page-design/.

Deadline: 30.01.2018.

**Comment by kominoshja** [comment]
This is already on it's way
P.S: This issue belongs on Identihub's repo, as it's specific to Identihub

**Comment by elioqoshi** [comment]
Yes, please track it here: https://github.com/uracreative/identihub/issues/27

Closing this
