### ISSUE TITLE
Ura website, add photo from Mariana

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#42]
@marianaballa add your photo at the 'team' section of www.ura.design website.
@AnXh3L0 please help with editing if needed. Outreach on Twitter needs to follow. 

Deadline: 18.01.2018

**Comment by AnXh3L0** [comment]
@rskikuli the photo of Mariana will be added as soon as she shoots one at Andis, the current ones she has are not high quality that we need for the website. For now, the website has only the 4 of us.

**Comment by rskikuli** [comment]
@marianaballa changing this as a high priority one. I'll talk to Andis and book a day for you to make the photo shooting.

**Comment by elioqoshi** [comment]
Can we please make sure Titles of issues are correct @rskikuli? Apart "ad" which has a typo, I think we agreed before that the title should start with the task and the bigger project should be after that. So it would be "Add Mariana's photo to the Ura Website"

**Comment by marianaballa** [comment]
Picture was added. I suggest we close this issue.
