### ISSUE TITLE
PGP email for Ura

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#43]
We need to have at least one email with PGP encryption for communication purposes with clients. Ideal scenario all our emails have this capability. 

Deadline: 22.01.2018.

**Comment by kominoshja** [comment]
I clearly missed this deadline. Will come up with the procedure in 15th of February

**Comment by kominoshja** [comment]
Unfortunately the email servers we use do not support any encryption except TLS handshakes. You can read more about it [here](https://help.zoho.com/portal/community/topic/able-to-send-encrypted-email-in-zoho-mail). Closing this issue since there's nothing we can do at this moment.

**Comment by elioqoshi** [comment]
Don't close this issue for that reason. This issue is not optional. Also the OP should be responsible for closing issues. Reopening.

**Comment by rskikuli** [comment]
@Borisbudini this is required for some of our current clients and also god for privacy. We need to have a solution by the end of February 2018.

**Comment by kominoshja** [comment]
This is technically impossible for as long as we use Zoho. 
On the other hand we can open a gmail account, but that wouldn't end with @ura.design

**Comment by kominoshja** [comment]
I need input on how we are going to proceed with this.

**Comment by rskikuli** [comment]
@Borisbudini can you please prepare to present the options that we have on this during the work week #59 ?

**Comment by kominoshja** [comment]
Yes! Definitively.

**Comment by AnXh3L0** [comment]
We are now using ProtonMail so our emails are encrypted. I believe we can close this issue now @rskikuli

**Comment by elioqoshi** [comment]
We can close this after @LuisTepshi and @Borisbudini uploaded their public keys and they show up on our team page. Additionally everyone should switch to our new signatures which include the PGP fingerprints.

**Comment by AnXh3L0** [comment]
All the PGP keys are now implemented in our website and the signatures too. This issue is now complete.

**Comment by rskikuli** [comment]
Please @marianaballa @AnXh3L0 @elioqoshi @LuisTepshi @Borisbudini confirm that you have the signature in your email.

**Comment by LuisTepshi** [comment]
Done.

**Comment by LuisTepshi** [comment]
? Dmth? Do te te vendosim rregull qe nuk mund te dergosh dot emaile me me pak se X karaktere :D

--
Redon Skikuli
Development & Outreach
Ura Design https://ura.design
PGP Key Fingerprint: 76E2 6021 8C89 98A2 6492 6B69 B0A8 131C F420 4416

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by AnXh3L0** [comment]
Yes, I have the signature in the email.

**Comment by elioqoshi** [comment]
This should be good to go now. We should schedule a training on how to use PGP and ProtonMail bridge once the documentation is online internally.
