### ISSUE TITLE
Add FOSS Asia case at Identihub homepage

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#44]
As part of our collaboration with FOSS Asia please add their case at Identihub homepage website by replacing Mozilla Reps page.

Deadline: 25.01.2018

**Comment by AnXh3L0** [comment]
FOSSASIA has been added in the website and has replaced Mozilla Reps, the link still points to Reps project but will be updated as soon as their assets are online.

**Comment by rskikuli** [comment]
Thanks. Please also change the text on mouse over.

**Comment by AnXh3L0** [comment]
Done. I believe the issue can be closed now because our part is done :)
