### ISSUE TITLE
Google Summer of Code 2018 Organization Application for Identihub

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#45]
Reply to the following questions:

- Why does your org want to participate in Google Summer of Code?
- How many potential mentors have agreed to mentor this year?
- How will you keep mentors engaged with their students?
- How will you help your students stay on schedule to complete their projects?
- How will you get your students involved in your community during GSoC?
- How will you keep students involved with your community after GSoC?
- Has your org been accepted as a mentor org in Google Summer of Code before?
- What year was your project started?
- Where does your source code live?

Internal deadline: 19.01.2018
Deadline from Google: 23.01.2018 at 17:00 UTC.

**Comment by rskikuli** [comment]
This is done. closing the issue. Thanks for the work @marianaballa @elioqoshi

**Comment by rskikuli** [comment]
Reopening this because forgot to have a follow up asking the organizers about the reasons that we did not get accepted, which will hep us apply with a better proposal for GSoC 2019. @elioqoshi since you applied I think you should be the one to follow up on this. Here is the contact page: https://developers.google.com/open-source/gsoc/contact
Here is the reply I sent for CityZen that might help you: https://pad.ura.design/p/GSoC-aplikim-Indetihub. Many thanks.

**Comment by rskikuli** [comment]
ping @elioqoshi . Did you proceed with this?

**Comment by rskikuli** [comment]
@elioqoshi any follow up?

**Comment by elioqoshi** [comment]
I received the same email from them after asking and it has been because of the list of things to work on. Closing this
