### ISSUE TITLE
Newsletter February 2018

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#48]
Preparation, development and send out of the second edition of our newsletter. Tasks include:

- content (most important story we want to share);
- structure (based on the first edition);
- testing;
- outreach (twitter etc);
- presentation on ura.design website (archiving);
- internal reporting. 

Deadline for preparation: 14.02.2018
Deadline for send out: 15.02.2018

**Comment by elioqoshi** [comment]
@rskikuli the deadlines don't make sense. What were they meant to be?

**Comment by rskikuli** [comment]
Preparation of everything is the core part of the job. Testing and send out is the other part of it.

**Comment by elioqoshi** [comment]
@rskikuli I mean the preparation deadline is after the send out deadline

**Comment by rskikuli** [comment]
corrected. Thanks.

**Comment by elioqoshi** [comment]
Looks good to me

**Comment by rskikuli** [comment]
Proposed content: 

- Fosdem presence (Identihub presentation);
- Identihub development updates;
- design work (very important to show some good design work we have done)
- other news we might have. 
- secondary thingies: Patreon, Twitter etc.

**Comment by elioqoshi** [comment]
Our new website will be a highlight as well.

**Comment by rskikuli** [comment]
@marianaballa I added my comments on the pad. Please review. 
@elioqoshi it is important to feature one of the design work done by us.

**Comment by elioqoshi** [comment]
Should be easy. Let's feature 2 works I propose.

**Comment by AnXh3L0** [comment]
The newsletter is ready, it will be sent on Monday, the issue will be closed after it has been sent successfully.

**Comment by marianaballa** [comment]
Newletter was sent. We should close this issue.

**Comment by AnXh3L0** [comment]
@rskikuli shall we close this issue?

**Comment by rskikuli** [comment]
Yes @AnXh3L0 . Closing this.
