### ISSUE TITLE
 Patreon updates for February 2018

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#49]
Monthly update for our Identihub patreons. Content will be agreed in the second week of February2018. 

Deadline for the content preparation: week 20.02.2017
Deadline for publication: 28.02.2017

**Comment by marianaballa** [comment]
Updates were posted o Patreon for February. 
[Join us at FOSDEM](https://www.patreon.com/posts/join-us-at-2018-16734784) blogpost, [Ura at FOSDEM](https://www.patreon.com/posts/ura-at-fosdem-17185254) report and [Inkscape workshop in Tirana](https://www.patreon.com/ura/posts) report.

I suggest we close this one.

**Comment by AnXh3L0** [comment]
@rskikuli is this complete?
