### ISSUE TITLE
FOSDEM 2018 presence

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#5]
Preparations and work for the presence before and after the activites of Ura crew at [FOSDEM 2018](https://fosdem.org/2018/) edition. Task will include:

- brainstorm for the presence of Ura at the event;
- preparations before the event;
- task assignments for activities during the event including photo documentation;
- logistics for travelling;
- blog post and promo after the event;

**Comment by elioqoshi** [comment]
We should apply with sessions at the Open Source Design track:
http://opensourcedesign.net/events/2018/02/04/opensourcedesign-fosdem-2018

- Identihub (Redon+Elio)
- WebVR for Designers (Elio)

Deadline is 1st December so we should do this tomorrow

**Comment by rskikuli** [comment]
@elioqoshi let's work on the draft proposal [here](https://pad.ura.design/p/Ura-presence-at-fosdem2018).

**Comment by rskikuli** [comment]
![fosdem ura submission from 2017-11-29 15-37-49](https://user-images.githubusercontent.com/17770262/33380462-72a75854-d51b-11e7-996c-9153f7335861.png). 
There is an image needed here. @elioqoshi do you have info on what this is about?

**Comment by rskikuli** [comment]
Is this done? @elioqoshi

**Comment by elioqoshi** [comment]
Image was not needed. Identihub proposal is sent and is good to go. If any info of it needs to be updated we can do that as well (I used the same description meant for 34c3)

**Comment by AnXh3L0** [comment]
As discussed, Ura crew members will also stay at the OSD booth, will give talks on Identihub and more. Tickets and accomodation should be almost done for everyone.

**Comment by kominoshja** [comment]
Closing this issue since FOSDEM is over

**Comment by elioqoshi** [comment]
@Borisbudini don't close it as it's really related to the communications group. If you read the OP you can see that it entails also a follow up after the event. Until these are done, this should stay open.

**Comment by marianaballa** [comment]
Blogpost/report for this was published today. You can find it here:  https://ura.design/2018/02/09/ura-fosdem-2018/

**Comment by AnXh3L0** [comment]
Is there anything left to do for this issue?

**Comment by elioqoshi** [comment]
@rskikuli let's close this

**Comment by elioqoshi** [comment]
Closing. If anything is left, please reopen.
