### ISSUE TITLE
 Media kit preparation for the website

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#51]
We might have some media requests in the following weeks which generates the need to have a dedicated page with promo materials that can easily  downloaded. The material might include, but not be limited to:  

- screenshots of the website; 
- screenshots of one of our casse studies;
- general info about the project (something like about us); 
- logos; 
- some photos from events we have participated; 
- any other idea you might have.

The press kit will be added to the website of the project. 
Deadline: March 2018

**Comment by rskikuli** [comment]
@marianaballa the deadline for this is in a few days. Let's work on Monday 20.03.2018 about this.

**Comment by elioqoshi** [comment]
Why would you add a mediakit when Identihub is designed for that? Would be a lost opportunity of dogfooding. You can access Identihub and add all these to the Ura Project

**Comment by rskikuli** [comment]
Makes sense. Closing this.
