### ISSUE TITLE
Add hourly backups on demo.identihub.co

### ISSUE THREAD

**Issue by kominoshja** [uradotdesign/task-management#55]
As it was discussed in the chat it is important that we add another point in the backup of Demo server. The hourly backups. As the demo server is the main point for new users to try identihub, we can not risk server intrusion even on an hourly basis.
Solution: Add hourly backups
Deadline: 05.03.2018

**Comment by rskikuli** [comment]
Isn't this sensitive in terms of our security @Borisbudini ? I mean having this as public info... Should we close/delete this issue?

**Comment by kominoshja** [comment]
Hey @rskikuli Thanks for bringing this point. It isn't sensetive at all since we have not disclosed anything about our mechanisms. However we should close this issue because it is completed.

**Comment by elioqoshi** [comment]
You cannot delete issues on GitHub also.
