### ISSUE TITLE
Translate Ura website in other languages

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#57]
We need to work on making the new ura.design website (launched in 2018) easy to translate in other languages starting from German language.  
Deadline: June 2018.

**Comment by rskikuli** [comment]
@Borisbudini we need to define the framework on how this is going to work. Can you please share some info on how this is going to work?

**Comment by AnXh3L0** [comment]
I have found a Jekyll plugin for this @rskikuli : https://github.com/vwochnik/jekyll-language-plugin, will try to implement it asap without breaking existing functionalities.

**Comment by elioqoshi** [comment]
@AnXh3L0 Thanks!

Should we try to have a dev staging area for this? @Borisbudini

**Comment by kominoshja** [comment]
@AnXh3L0 So is this integratable with services that allow online contribution?
@elioqoshi Yeah it seems about time to start this.

**Comment by AnXh3L0** [comment]
@Borisbudini by default it is not, but I'll try to make it happen (for platforms like Hosted Weblate or similiar). Having a dev staging for this would be nice so I can experiment on it and then can easily push them to master when ready.

**Comment by rskikuli** [comment]
Would it be realistic to say that we will be able to have implemented the translation of the website in one more language in July 2018?

**Comment by kominoshja** [comment]
I'd say it would be realistic. We need to get started on this at the Work Week

**Comment by elioqoshi** [comment]
I'd hope sooner than July. Let's aim for having it l10n ready in April (needed infrastructure set up) and first language (German) up by end of May.

**Comment by rskikuli** [comment]
@Borisbudini an update on this?

**Comment by marianaballa** [comment]
After discussing with @rskikuli and @Borisbudini we will do the last planning on Monday 04.06.2018. After testing the website will be translated in Albanian by 1.07.2018.

**Comment by elioqoshi** [comment]
Might be a bit too much work and we need better content before translating. We could revisit this in 2019
