### ISSUE TITLE
Work Week Spring 2018

### ISSUE THREAD

**Issue by marianaballa** [uradotdesign/task-management#59]
As we discussed yesterday on our weekly virtual meeting, we are planning a working session again. This means that we are going to spend more hours together and work on our assigned tasks. 

@elioqoshi proposed to have this work week outside of Tirana. The proposed cities were Shkodër (Albania) and Pristina (Kosovo). Although, we didn't decide anything yet.

Personally, I'd choose Pristina so we can also meet with the local FOSS community. But, I'd love to hear your proposals too. @Borisbudini @elioqoshi @rskikuli @AnXh3L0  :)

As possible dates, I'm proposing April 14-15 or April 21-22.

**Comment by kominoshja** [comment]
I'd like Prishtina as well

**Comment by AnXh3L0** [comment]
I'd also vote for Pristina and on April 21-22 :)

**Comment by rskikuli** [comment]
I would propose Durres since the weather is nicer than Prishtina and we have the sea as a bonus. Can't say about the logistics though with the quality of the hotels being the main issue. The weather is nice now and would be a shame not to spend it by the sea. One more thing: I would propose to add Friday as a workday and have Sunday as a more chilled day for the team. 
Regarding the dates: I'm fine with all options, but I would propose to go for something that is closer. The earlier the better.

**Comment by rskikuli** [comment]
@marianaballa please prepare meeting notes pad and share it with team members via email. It should be easy for anyone to propose issues that needs to be discussed. Of course add your own issues as well. Many thanks!

**Comment by elioqoshi** [comment]
I am fond of Durres although I do not know what the weather will be like (I suspect better than Prishtina anyway). @Borisbudini can we work at Studio maybe? Ideally we should work in the AirBnB too.
@marianaballa sponsored dinner on saturday and drinks on sunday I'd say

**Comment by kominoshja** [comment]
We can work at Studio, however if we want wifi we have to sit inside where the tables are small

**Comment by marianaballa** [comment]
On our weekly meeting, we agreed to have Work Week during April 21-22.

**Comment by elioqoshi** [comment]
That includes also Friday 20th as a warm up. @marianaballa please explore apartment options for us close to the center/sea shore

**Comment by rskikuli** [comment]
Also @Borisbudini please take the lead on this for many of the logistics in coordination with @elioqoshi.

**Comment by rskikuli** [comment]
@Borisbudini @marianaballa @AnXh3L0 please start a list of issues at a personal or team level so that we talk about this during the WW. Share it by email please. Thanks.

**Comment by rskikuli** [comment]
@marianaballa start preparing a blog post about this?

**Comment by marianaballa** [comment]
The blog post will be published on week 04.06.2018. Draft text will be shared on our chat by Monday 04.06.2018 the latest.

**Comment by elioqoshi** [comment]
@marianaballa please check in with @AnXh3L0 and @rskikuli to review the draft as well.

**Comment by elioqoshi** [comment]
We lost momentum on this so let's move on.
