### ISSUE TITLE
Chaos Communication Congress (34C3) presence

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#6]
Preparations and work for the presence before and after the activites of Ura crew at [34C3 edition](https://events.ccc.de/congress/2017/wiki/index.php/Main_Page). Task list will include:

- brainstorm for the presence of Ura at the event;
- preparations before the event;
- task assignments for activities during the event including photo documentation;
- logistics for travelling;
- blog post and promo after the event;

**Comment by AnXh3L0** [comment]
Elio was present at 34C3, the blog post for this should be in our website soon.

**Comment by rskikuli** [comment]
This is now published: https://ura.design/2018/01/15/chaos-communication-congress-2017/. Closing this.
