### ISSUE TITLE
Blog post about accepting crypto-currencies

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#62]
Following our decision to accept cryptocurrency please proceed with a dedicated blog post about this. @AnXh3L0 also please support it with an image. 

Deadline: 31.03.2018.

**Comment by elioqoshi** [comment]
The deadline for this was Monday (26th March)  and it's not a Medium priority but overdue.

**Comment by marianaballa** [comment]
Deadline for this blogpost was not Monday. At first, we agreed on Monday to publish a tweet for this. Afterwords, we agreed to publish a more detailed blogpost on the website. The text for this from my side will be ready in a couple of hours.  Once we have the image mentioned above by Redon, we are ready for publication.

**Comment by elioqoshi** [comment]
No, I didn't say that.

![image](https://user-images.githubusercontent.com/5436686/38137482-1e56e418-3425-11e8-8cd9-f455cd4a66ec.png)

I was referring to actual posts, not tweets. Tweets don't need an outline. Seems that was not understood, I will try to be more clear about this in the future.

**Comment by rskikuli** [comment]
The draft is on the pad with changes based on the chat comments. @AnXh3L0 please also share the image you are working on so that we publish this - Anxhelo please show to Mariana how to add directly blog posts using the new website infrastructure. Thanks.

**Comment by AnXh3L0** [comment]
I believe this is now complete - shall we close this?

**Comment by rskikuli** [comment]
Yeap. Everything is online https://ura.design/2018/03/31/introducing-cryptopayments-for-our-services. Thanks everyone for the involvement.
