### ISSUE TITLE
 Blog post about Identihub presence at OSCAL 2018

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#64]
We will be present this year at OSCAL with an info booth. Let's work on a blog post that will show our presence there. Help with photo editing needed from @AnXh3L0.

Deadline for draft: 25.05.2018.

**Comment by elioqoshi** [comment]
Just to make sure, this is a post-report?

**Comment by rskikuli** [comment]
Yep. It makes more sense IMO.

**Comment by marianaballa** [comment]
Just noticed that this overlaps with #65 

Closing this as well.
