### ISSUE TITLE
OSCAL 2018 presence

### ISSUE THREAD

**Issue by marianaballa** [uradotdesign/task-management#65]
As OSCAL 2018 is approaching we need to start our preparations for our presence there. We will have our own infobooth for Identihub and we  have to agree on the swag we will have. Proposed set up:

- table cloth 

- roll-up banner

- stickers

- tablet and/or laptop for website and case-studies of organizations/companies using Identihub

- registration form for our newsletter (printed or through the laptop)  

- giveaway for the draw (ex.  raspberry pi or Yubikey)

- candies/drinks

Approximate costs for the above is 200 USD, including table cloth, roll- up banner, giveaway gift and unexpected costs. 

Deadline for cost approval or feedback related to the costs: April 4.

**Comment by elioqoshi** [comment]
I don't see a cost breakdown for this and considering that we are not profitable yet, I would cut these costs in half.

- Roll-up Banner (approximately 50-60 USD)
- I have a tablet and we can find a laptop as well
- Candies and Drinks shouldn't cost too much as well (max 40 USD for both days)
- Not sure how Hardware is related to Identihub. We can do a giveaway of Stickermule credits which I can request.

That puts as at a budget of 100 USD. If there is any other expected costs, @marianaballa just let us know and we will figure it out of course.

This should go through approval of @rskikuli as well

**Comment by marianaballa** [comment]
We had a report published (https://ura.design/2018/05/31/oscal-18-we-were-there) on the blog for our presence at OSCAL. 

I'm closing this issue.

**Comment by rskikuli** [comment]
Please also share on Twitter and close it afterwards.

**Comment by marianaballa** [comment]
We had this blogpost featured on our Twitter account with a dedicated tweet ( https://twitter.com/uracreative/status/1006225211023331331 ).
