### ISSUE TITLE
Thunderbird project press release

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#66]
We need to work on a press release on the work we are doing for Thunderbird and make this as the main work to be presented in May 2018. More detailed brief will follow. 

**Deadline for first draft: 2.05.2018**
**Deadline for publication: 15.05.2018**

**Comment by marianaballa** [comment]
On the blog post I'll include:

- logo redesign;
- styleguide;
- usability research;
- new website (spoiler with not much details).

Let me know if I'm missing something guys.

**Comment by elioqoshi** [comment]
This is done: https://ura.design/2018/07/05/thunderbird-style-guide
Closing
