### ISSUE TITLE
Moving domain

### ISSUE THREAD

**Issue by kominoshja** [uradotdesign/task-management#67]
Sinve we have expanded our sysadmin team, the current domains config do not make sense. We should move them to a new management platform. However this would render **ALL** of our services down for a maximum of 48h. Would be ideal to do this before the workweek. 
Any suggestion for the movement date?

**Comment by kominoshja** [comment]
Ping @elioqoshi

**Comment by rskikuli** [comment]
We should avoid days when we have big announcements, events (OSCAL is the closest in our calendars) or newsletter send out.

**Comment by elioqoshi** [comment]
@Borisbudini feel free to meet with me this week ideally and we can do it in person.

**Comment by kominoshja** [comment]
Maybe it would be a good idea to do it after workweek. That way we also add our new mail server only once

**Comment by AnXh3L0** [comment]
Did we finish this task already? Can we close it @Borisbudini ?
