### ISSUE TITLE
 Blog post about the new Enigmail visual ID 

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#68]
We are proud to have worked on the new logo for Enigmail, the integrated security add-on for Mozilla Thunderbird. It allows you to use OpenPGP to encrypt and digitally sign your emails and to decrypt and verify messages you receive. With this blog post we want to show the work we have done (how it was and how the logo is right now) and why we are (obviously) proud to add this on the list of projects we also use to exchange privacy sensitive information. Website, where also the new logo is present: https://enigmail.net/index.php/en/

Deadline for draft: 21.04.2018 (let's work on this during work week ans review the process of how we work on blog posts).
Deadline for publishing: 27.04.2018

**Comment by elioqoshi** [comment]
It's not a visual identity yet. It's just a logo and revamped icons. That's worthy itself though. We should add it to our portfolio as well I suppose. 

The link to the work documented is here: https://github.com/uracreative/works/issues/2

**Comment by AnXh3L0** [comment]
Enigmail is now on our portfolio page.

**Comment by elioqoshi** [comment]
In the future when we might do more work with Enigmail, it might be worth writing a post about it. Closing this.
