### ISSUE TITLE
Expenses and reimbursement procedures

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#69]
Creation of a template for requests from partners and employees related to reimbursements or upfront payments for expenses. Also the process should be documented for internal usage (using Gitlab @Borisbudini?)

Deadline for template(s): 18.04.2018
Deadline for internal documentation of the process: 30.04.2018

**Comment by rskikuli** [comment]
Template is on our cloud page. Documentation is in progress.

**Comment by elioqoshi** [comment]
Ping Boris when the documentation is ready @rskikuli

**Comment by rskikuli** [comment]
Where do I add the text for documentation about this @Borisbudini? Is there a link?

**Comment by kominoshja** [comment]
@rskikuli: @marianaballa should be able to help you with that since she's doing the operation documentation.

**Comment by marianaballa** [comment]
This one was included on our internal (private) documentation under the "Reimbursements" category.

I suspect we can close this issue now.

**Comment by elioqoshi** [comment]
Dependent on this https://github.com/uracreative/task-management/issues/85
Indeed this can be closed
