### ISSUE TITLE
Price list for design services

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#7]
Based on the discussion during the November 2017 work week we need to finalise the pricelist related to the services. The list includes, but it is not limited to the following tasks:

- logo design;
- full visual design proposal;
- UX services;
- web design;
- consulting fee(s) related to design;
- other (add details here)

The pricelist also should include details about:
- legal requirements; 
- payment method(s);
- all other comments that need to be clarified.

The outcome of the pricelist should be a well designed PDF file that can be easily sent to potential clients.

**Comment by elioqoshi** [comment]
Can you please share examples of how this price list would look like? I'm quite doubtful about the approach and want to be sure that we are following best practices here, not only from a studio perspective, but also open source community perspective

**Comment by elioqoshi** [comment]
Currently irrelevant and not a priority.
