### ISSUE TITLE
Cloud house keeping

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#71]
We need to get organized a little bit more on our cloud platform. Please propose a structure for organizing the files and also proceed with house keeping once you get approval. Many thanks. 

Deadline: 8.05.2018.

**Comment by rskikuli** [comment]
@Borisbudini please put this as a priority on your agenda. Ping @elioqoshi, myself and team when this is finished. 
New deadline: 29.05.2018.

**Comment by rskikuli** [comment]
Also @marianaballa we need your engagement on this.

**Comment by elioqoshi** [comment]
This should be mainly @marianaballa task as it's related to content and information structure rather than technical infrastructure.

**Comment by kominoshja** [comment]
@marianaballa I'm available 24/7 for any help you need

**Comment by marianaballa** [comment]
For our cloud service I would like to propose the following: 

- On the default folders (Photos and Documents) I propose to store accordingly the pictures we use for documentation (ex. events' photos, blogposts' pictures, etc) and any internal documents (ex. reimbursement form).

- Everything else that doesn't fit any of the above categories should be placed on the "Team" folder. Within that, we can have other folders with descriptive names for specific documents. 

- In case of a certain large project that we are going to have many different materials, we need to create a new, separate folder.

If you are thinking anything else please let me know.

**Comment by kominoshja** [comment]
I don't have anything to add to this, I think we should start integrating this.

**Comment by rskikuli** [comment]
@marianaballa the structure I propose is as following:
- clients > client name >> project name >>> creatives, legal, client material, outreach and 'other' sub folders (only final materials are saved here)
- transfer area (materials that are not final go here. Consider this as a 'wetransfer' service. Materials that are saved here get deleted every 6 months by the infra team)
- Events >> event name >>> Documentation, outreach, 'other'
- Internal >> Team (team photos etc) >> Outreach (interviews and materials handy for outreach) >> Portfolio (a PDF and other images that we need to have handy) >> 'other' folder. 

What do you guys think?

**Comment by rskikuli** [comment]
@marianaballa can we close this before 5.06.2018?

**Comment by rskikuli** [comment]
Ping @marianaballa . Also update the team about the new structure and make sure everyone understands the changes. Many thanks.

**Comment by marianaballa** [comment]
I implemented Redon's suggested schema. Please let me know if you have an other suggestion or otherwise we can close this.

**Comment by marianaballa** [comment]
As we discussed together with Redon and Elio, not everyone has the same view of the folders on our cloud due to the permissions each one of us has. 

I implemented the above schema and shared it with everyone. Also, I have added "Read me" files for easy comprehension.

**Comment by marianaballa** [comment]
I will wait for comments/suggestions on this until 15/06/2018.  :)

**Comment by rskikuli** [comment]
Checked on Sunday and looking good on my side. Thanks Mariana.

**Comment by marianaballa** [comment]
Closing this.
