### ISSUE TITLE
OTF report May 2018

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#72]
Documentation for monthly report of activities of Ura Design as part of OTF. Please add here on bullet points every time we have done tasks related to OTF.
Deadline: 26.05.2017

**Comment by elioqoshi** [comment]
@rskikuli this is overdue as well. Can we have a draft ready for tomorrow? 

I'd suggest these points:

- Reproducible Builds
- Thunderbird
- I2P
- Identihub Full-stack dev position
- OSCAL'18 report
- Newsletter

and anything else you might suggest

**Comment by rskikuli** [comment]
Report is sent. Thanks all for the involvement. Closing this.
