### ISSUE TITLE
OTF report June 2018 

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#73]
Documentation for monthly report of activities of Ura Design as part of OTF. Please add here on bullet points every time we have done tasks related to OTF.
Deadline: 26.06.2018.

**Comment by elioqoshi** [comment]
We should add also Thunderbird which is almost wrapped up. But I need to finish the style guide post first.

**Comment by elioqoshi** [comment]
We will probably be a few days late on this considering the Thunderbird work and the style guides blog post should be included and it's also a few days late

**Comment by rskikuli** [comment]
Adding #96 to the list of the things we are going to report.

**Comment by rskikuli** [comment]
@elioqoshi agree about Tunderbird, but is only one of the things that needs to be included. @marianaballa @AnXh3L0 please your update here about things that have been implemented.

**Comment by elioqoshi** [comment]
Draft here:
https://pad.ura.design/p/OTF-Report-June2018

**Comment by elioqoshi** [comment]
This is sent. Closing
