### ISSUE TITLE
Luis new member of our team

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#74]
As we now have Luis joining our team we need to introduce him as a new member with a dedicated blog post and also add his photo at our website. Please arrange photo shooting session at our photographer. We also need to share the news on our social media. 

Deadline: 15.05.2018

**Comment by marianaballa** [comment]
Will skip the blog post based on discussion with @elioqoshi and will proceed on announcement on social media only. Deadline: 2.06.2018.

**Comment by marianaballa** [comment]
We had a tweet featuring Luis' addition on the team. 

I suggest we close this of there is nothing else left.
