### ISSUE TITLE
Docker image for Identihub blog post

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#76]
After finishing the work for our docker image for Identihub we need to spread the word about it on our blog and social media. Details about the project are published here: https://github.com/uracreative/identihub/pull/125#issuecomment-386029349

Deadline for draft: 1.06.2018
Deadline for publishing: 6.06.2018

**Comment by elioqoshi** [comment]
I don't think this should be on the Ura blog itself unless it's part of a bigger release. The Docker image is also not at all reviewed (@Borisbudini ?) so we should close this as it has been 2 months already.

**Comment by kominoshja** [comment]
Yeah the docker image will probably be ready for the first release. We can add it as part of the blog post about our first release
