### ISSUE TITLE
Add news section on Identihub website

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#77]
At Ura.design blog section we have some blog posts related to Identihub. Would be nice if we cloud link to these blog posts from Identihub website. 

Deadline for proposals: 11.05.2018 
Deadline for going live: 18.05.2018

**Comment by kominoshja** [comment]
Are you proposing for Identihub to have it's own blog page, with articles written by the Identihub team; or are you referring to having a hub where we link articles about Identihub?

**Comment by rskikuli** [comment]
The second option sounds easier to implement and also better if there are going to be plans for a brand new website in 2018.

**Comment by rskikuli** [comment]
@Borisbudini we will need a dedicated blog section at the website. Let me know how it can be implemented.

**Comment by elioqoshi** [comment]
If it's about a dedicated blog section on the Identihub landing page, it's unrelated to this task tracker and should be closed. An issue in the landing page repo can be created.
