### ISSUE TITLE
Newsletter infrastructure setup up

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#8]
Following the discussions during Work Week 2017 in November we will proceed with the set up of the newsletter infrastructure and templates needed for the send out of the monthly newsletter. A newsletter sign in for should also be incorporated in 

### 
Tasks:

- platform research and proposal: @Borisbudini & @AnXh3L0 
- email/newsletter setup: @Borisbudini 
- newsletter template: @AnXh3L0 
- newsletter list of recipients (including categorisation): @silvaarapi 
- incorporation of the newsletter sign in for into ura.design website: @silvaarapi

**Comment by silvaarapi** [comment]
I did some testing about the platform we should use to sent the newsletters. I would go for Tinyletter after comparing it with MailChimp and phpList. The application is very simple and easy to use, and offers all the features we need to sent our newsletters so I think it's a good option. Also did some research and it seems to be easy to migrate our lists to MailChimp if we might need go for bigger campaigns in the future.

**Comment by elioqoshi** [comment]
Let's go ahead with it then. @Borisbudini can you set up an account and give access @silvaarapi ?

Once we are in the flow of sending out newsletter regularly, we should consider switching to phplist, but once we are sure that we are actually able to deliver consistent communication

**Comment by kominoshja** [comment]
We now have an account in TinyLetter. I suppose we can close the issue until we need it.

**Comment by elioqoshi** [comment]
This should be closed after everything in https://github.com/uracreative/task-management/issues/8#issue-277459961 is done

**Comment by rskikuli** [comment]
Since the first newsletter is sent I'm closing this one.

**Comment by marianaballa** [comment]
As discussed on our last online meeting, April's newsletter will be sent from phpList.  @Borisbudini please create a new account for Ura on phpList.

Deadline: 07-03-2018

**Comment by kominoshja** [comment]
@marianaballa I tried to set up our account but it seems that there is something wrong with phpList. It doesn't seem to be able to create an account at this time(I tried admin, boris and even my personal email, yet all three of them failed) Maybe we should contact the maintainers?

**Comment by rskikuli** [comment]
@Borisbudini an update here please. Thanks.

**Comment by kominoshja** [comment]
Hey @rskikuli. As i said in the chat i'm waiting for you to tell me if you received the confirmation email.

**Comment by kominoshja** [comment]
@rskikuli Reminder on this

**Comment by rskikuli** [comment]
@Borisbudini please ping Suela directly for this. She has the needed info.

**Comment by elioqoshi** [comment]
This could be closed since we use phplist.com anyway
