### ISSUE TITLE
Stickermule Order June 2018

### ISSUE THREAD

**Issue by elioqoshi** [uradotdesign/task-management#81]
We should order new materials from stickermule. Let's decide on the products and the artwork used here.

**Comment by elioqoshi** [comment]
300 ft packaging tape: 39$
https://www.stickermule.com/products/packaging-tape

**Comment by elioqoshi** [comment]
200 Thunderbird 2x2in magnets: 115$

**Comment by marianaballa** [comment]
Is this issue overlapping with issue #75 ?

**Comment by rskikuli** [comment]
It seems so. Thank for noticing Mariana. Once this is done I'll close both issues.

**Comment by rskikuli** [comment]
Sorry for the second comment. Just wanted to add that I love the packaging tape. It will be handy for events we participate in the near future.

**Comment by elioqoshi** [comment]
Here is my order proposal with a mockup of the swag on the side. Let me know if you suggest any change

![image](https://user-images.githubusercontent.com/5436686/40795430-5ae25b52-6502-11e8-9bd3-85319cd87cd8.png)

**Comment by rskikuli** [comment]
+1 from my side.

**Comment by rskikuli** [comment]
Sorry for the second comment. Just wanted to add that I love the packaging tape. It will be handy for events we participate in the near future.

**Comment by elioqoshi** [comment]
This is finished and will arrive at Mariana's place in Greece by 28th June. Thanks for everyone involved!

**Comment by elioqoshi** [comment]
Also thanks to @jdorfman for the sponsorship :)
