### ISSUE TITLE
Work Week Summer 2018

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#82]
Summer is here and also the season of a new Ura Work Week. This means that we are going to spend more hours together and work on our assigned tasks.
@elioqoshi available budget (if any)? Also you had some thoughts on making this process even more productive. Please share. 
All team: based on available budget we need to think of location and also an agenda, which needs to be really tight this time. 

Deadline to finalize location and dates: 01.06.2018

**Comment by kominoshja** [comment]
Spoiler: I don't have a source on the costs.
I heard the south might be nice around this time of year and Corfu might be a good location for workation and not very expensive

**Comment by elioqoshi** [comment]
We need a good internet connection and I'm not sure how well the south of Albania is for that.

I will need to check about the budget and see what we can allocate to this. Ideally, I'd like us to stay 4 nights there so we can have actual progress. The middle of the year work week should be hands-on while the end of the year one should be strategy focused and celebratory. Hence I'm not sure if the south, sun and beach are the best for that. I am still fond of Prishtina as a place to go.

**Comment by rskikuli** [comment]
I also think the sun and crowded with tourists places are not very ideal for our purpose.

**Comment by kominoshja** [comment]
Actually it's cooler (weather wise) in Prishtina so that seems like a good idea.

**Comment by marianaballa** [comment]
I would like to propose Shkodra or Korça for the next work week. None of them is quite populated around this period of time and especially Korça is quite cool during summer time.

**Comment by rskikuli** [comment]
Team members will be in Prishtina at least one more day so it might be too mutch. On the other side there is a new team member based in Prishtina at the moment and hosting it there might help team building. Korca is a good option, I prefer it more than Shkodra, but it is more expensive which is something we should take into consideration.

**Comment by marianaballa** [comment]
We decided to have our Work Week in Prishtina, Kosovo. 
Dates: 
Departing from Tirana on August 15th and coming back in Tirana on August 20th.
We booked our hostel today during our meeting. Within the following days we will prepare the agenda.

**Comment by rskikuli** [comment]
Ping @RenataGegaj to see the thread here :)
@marianaballa please start a pad and share a link using our emails. Team @elioqoshi @Borisbudini @AnXh3L0 @RenataGegaj @LuisTepshi please add your comments on the pad that will be shared by Mariana.

**Comment by elioqoshi** [comment]
This is over.
