### ISSUE TITLE
Open Source Design Summit 2018 

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#83]
Team we have to start getting organized for the second edition of Open Source Design Summit that this year will take place in Tirana, Albania. @elioqoshi please share some useful links and also any proposal you have in terms of what needs to be done from the team - as a general overview not in details I wold say. Thank you.

**Comment by elioqoshi** [comment]
Everything is public on the Open Source Design repos and forums. I have had no private talks with anyone to be a blocker of information. You can find all the information here: https://github.com/opensourcedesign/organization/issues/103

**Comment by rskikuli** [comment]
True, but I suppose the tasks of the local team are different from the guests. If you think there is no reason to talk about the local team here let's close this.

**Comment by elioqoshi** [comment]
No we should keep this open here but I have no other news apart what's discussed in that thread

**Comment by marianaballa** [comment]
I agree with Redon here. As OSCAL the largest part of our team was involved in organizing OSCAL and now that it is over, we can start with preparations for OSD Summit 2018. 

As far as I can remember, Elio had mention that this event is not a large conference but more like a meet up. To me, Protik seems a great option for the venue (judging by my experience at OSCAL).

**Comment by rskikuli** [comment]
Oficina has becoming again as an option btw since Lib0con will propably be hosted there.

**Comment by rskikuli** [comment]
Guys if Oficina is the venue we are interested in we need to sign an agreement with them. Let me know if this is the case and I'll proceed with the draft.

**Comment by elioqoshi** [comment]
From our discussions the other day, most preferred Protik @rskikuli

**Comment by rskikuli** [comment]
Ok so, I'll talk to them for a written agreement about this. I should have a draft somewhere. Will update the progress here.

**Comment by elioqoshi** [comment]
Thanks, appreciated

**Comment by elioqoshi** [comment]
This has been a success, thanks to everyone involved! Some wrap up and blog post is tracked here:
https://github.com/uracreative/task-management/issues/103
