### ISSUE TITLE
Insignary website updates and new designs

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#84]
As mentioned during our internal communication please proceed with the new updates of the website based on the comments and requests from our partner. 
Deadline; 22.06.2018

**Comment by rskikuli** [comment]
Please proceed with the additional images based on the approved first one as mentioned from the email from the client at 31.05.2018 @AnXh3L0

**Comment by rskikuli** [comment]
Based on the latest update please prepare to wrap up the project until week 25.06.2018. Thank for the work so far @AnXh3L0 .

**Comment by rskikuli** [comment]
@elioqoshi blog post or Twitter mention about this? I think we need a blog post. Ping @marianaballa to follow the discussion and take action.

**Comment by elioqoshi** [comment]
There is not much of a story to tell I think. They had a specific set of changes required and we implemented them. We should add it to our Portfolio though @AnXh3L0

**Comment by elioqoshi** [comment]
Also, to track progress of design work itself, we should use the /works repo: https://github.com/uracreative/works

**Comment by AnXh3L0** [comment]
This project has been completed a while ago; closing the issue.
