### ISSUE TITLE
Internal Standard Operating Procedures

### ISSUE THREAD

**Issue by marianaballa** [uradotdesign/task-management#85]
On our meeting yesterday we agreed to have a specific rhetoric when it comes to the communication with third parties. We need to have two different guides. 

**Blogposts**: here we should include the words/ phrases/ expressions that describe us the best and have them as templates for feature blogposts/ social media outreach.

**Presentations/Infobooth**: here we should include our rhetoric when it comes to what we do as an agency in general, how to present our portfolio/ software in events and discussions. 

This should be only for internal use, therefore it should be on our GitLab instance.

**Comment by elioqoshi** [comment]
I had a look at the things and they looked solid! There are some small typos which would be good to be fixed and the main page of the handbook should offer some introduction instead of just a list of all different things it covers.

**Comment by elioqoshi** [comment]
Done
