### ISSUE TITLE
Invoice platform update

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#87]
Please proceed with the update of our invoice platform. 
Deadline 07.06.2018

**Comment by elioqoshi** [comment]
We also need a new account created for @rskikuli

**Comment by elioqoshi** [comment]
I created an account for Redon

**Comment by LuisTepshi** [comment]
Completed

**Comment by rskikuli** [comment]
@LuisTepshi issues are in general closed by the person that opens them after everything is implemented. Thank you.
