### ISSUE TITLE
Onboarding Renata 

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#88]
We are happy to officially have on board of our team @RenataGegaj as a Usability Researcher. 
Let's congratulate her by helping with anything she needs and also:
- give her access to our online infrastructure @LuisTepshi (Mattermost chats, GitHub team (only relevant repos -ask me), GitLab (same approach with GitHub);
- dedicated email account (@LuisTepshi please coordinate with @elioqoshi about the pricing plan of our email provider);
- online security (@Borisbudini please coordinate with me and @LuisTepshi on the infra chat)
- official announcements (@marianaballa you know the steps, including profile pic and of course a dedicated blog post mentioning our long time vision of having Usability Research as a 'on default' process for free open source projects and the importance of having a dedicated expert full time as part of our team);
- legal and finance related things including reimbursement procedures (@rskikuli and @elioqoshi )
- information about work week details (@redon).
- Anything else I'm missing 

Most important let's make her feel 'home'. Faleminderit,

**Comment by rskikuli** [comment]
@LuisTepshi please a status update on this before the end of week 18.06.2018.

**Comment by elioqoshi** [comment]
There is no update he can provide without Renata having a ProtonMail account yet.

**Comment by rskikuli** [comment]
I think we have ProtonMail now. Can @LuisTepshi take lead of this?

**Comment by rskikuli** [comment]
We need to move faster on this. Changing the priority. 
Deadline for thew whole process: 29.07.2018

**Comment by LuisTepshi** [comment]
I'm giving her access to our online infrastructure (mattermost, gitlab,github).

**Comment by AnXh3L0** [comment]
Did Renata get access in everything? @LuisTepshi

**Comment by LuisTepshi** [comment]
Yes. Mattermost, nextcloud, gitlab.

**Comment by elioqoshi** [comment]
She is onboarded fully now for some days. Closing this.
