### ISSUE TITLE
Finding incentives for usability research participants

### ISSUE THREAD

**Issue by rskikuli** [uradotdesign/task-management#89]
As part of all our activities related to usability research we need to find incentives for participants of all the lab sessions we are planning to organize. Please add ideas based on how easy it is to find incentives in terms of logistics and likability from participants. Some ideas include gits cards from Adrion bookshop, gift cards from Gjirafa50, or tshirts and/or tote bags. @Renatagegaj your input is also needed.

Deadline: 15.06.2018.

**Comment by elioqoshi** [comment]
We are thinking to do gift cards or small payments for testers.
