### ISSUE TITLE
Newsletter - July 2018

### ISSUE THREAD

**Issue by marianaballa** [uradotdesign/task-management#91]
- I will start preparing June's newsletter but I need a "brief" on the content. Any Identihub updates, projects to be featured, new additions to the team, etc. I'm creating a pad to work on this and share the link internally. Please add there your points. 

- My second point is whether we are going to send the upcoming newsletter from phpList. According to their pricing page (https://www.phplist.com/pricing) we can get the free plan for 300 messages and 500 subscribers. I believe that this plan works fine for now and if necessary we can upgrade our plan in the future.

**Comment by rskikuli** [comment]
Mariana please don't forget to add labels to the issues :)

Deadline for draft: 22.06.2018
Deadline for phpList implementation: 22.06.2018
Deadline for send out: 26.06.2018.

**Comment by elioqoshi** [comment]
@marianaballa @rskikuli  can you start creating a design layout for the newsletter in phpList?

**Comment by marianaballa** [comment]
I did a little bit of a research and I found a template. It's similar to the structure we had on the previous newsletter but we can add more images here.  Feedback is appropriated. 

[NL-layout.zip](https://github.com/uracreative/task-management/files/2136915/NL-layout.zip)

**Comment by elioqoshi** [comment]
We will miss June so let's push this for July

**Comment by elioqoshi** [comment]
We are doing a break with newsletters for now.
