### ISSUE TITLE
UX & Product Munich #12 - Talk about Identihub

### ISSUE THREAD

**Issue by elioqoshi** [uradotdesign/task-management#96]
I will be talking on 28th June at 7pm Munich time via Hangouts at UX & Product Munich. It will be a short talk covering our work at Ura in relation to Open Source Design and a live demo of the new features of Identihub currently on the test server.

Meetup page:
https://www.meetup.com/MunichUX/events/248097433/

Identihub Live Demo Test:
https://www.meetup.com/MunichUX/events/248097433/

I will do a tweet later on this

**Comment by rskikuli** [comment]
Please don't close this @elioqoshi until the OTF monthly report is sent out. Thanks.

**Comment by rskikuli** [comment]
Can we close this now @elioqoshi ?
