### ISSUE TITLE
Install Collabora Office and link with Nextcloud

### ISSUE THREAD

**Issue by elioqoshi** [uradotdesign/task-management#99]
I think it would be worthwhile to work on spreadsheets together and similar documents with Collabora Office via Nextcloud. This would require a separate droplet on DigitalOcean (rather higher performance) which needs to be linked with the current DigitalOcean.

**Comment by LuisTepshi** [comment]
I installed Collabora and linked with Nextcloud.

**Comment by elioqoshi** [comment]
@LuisTepshi please test it before. I get this error:
![image](https://user-images.githubusercontent.com/5436686/43033743-89a1f52a-8ccf-11e8-8a46-348c2a91fae8.png)

**Comment by elioqoshi** [comment]
@LuisTepshi This has not been fixed and it was quite urgent before everyone went on vacations...

**Comment by kominoshja** [comment]
Installed. Please close this.

**Comment by elioqoshi** [comment]
Thanks!
